[book]
authors = ["9kin"]
language = "ru"
multilingual = false
src = "src"
title = "is-algo"


[output.html]
git-repository-url = "https://github.com/9kin/is-algo"
edit-url-template = "https://github.com/9kin/is-algo/edit/master/{path}"
additional-css = ["theme/style.css", "./mdbook-admonish.css"]
additional-js = ["theme/sidebar.js"]

[preprocessor.quiz]

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

[preprocessor.katex]
block-delimiter = { left = "$$", right = "$$" }
inline-delimiter = { left = "$", right = "$" }
after = ["links"]
no-css = false
include-src = false

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.0"

[preprocessor.utils]
command = "python3 utils/preprocessor.py"