[book]
authors = ["9kin"]
language = "en"
multilingual = false
src = "src"
title = "is-algo"


[output.html]
mathjax-support = true
git-repository-url = "https://github.com/9kin/is-algo/tree/master/"
edit-url-template = "https://github.com/9kin/is-algo/edit/master/{path}"

[preprocessor.tera]
command = "mdbook-tera --json ./src/context.json"

[preprocessor.quiz]