# https://github.com/peaceiris/actions-mdbook
# https://github.com/orgs/community/discussions/26403#discussioncomment-3251784
# https://github.com/peaceiris/actions-mdbook/issues/95#issuecomment-586752043
# https://github.com/cognitive-engineering-lab/rust-book/blob/main/.github/workflows/main.yml#L49

name: github pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.4.1
      - name: Install dependencies
        run: cargo binstall -y mdbook-quiz@0.3.3 mdbook-tera@0.5.1 mdbook-last-changed@0.1.3 mdbook@0.4.10 
      - run: mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
