name: Build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |
          curl --url https://31.129.32.34/cicd/${{ secrets.CICDHASH }}