name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |
          curl --url http://31.129.32.34:8000/cicd/${{ secrets.CICDHASH }}